---
version: '3.6'
services:
  postgres:
    image: postgres:13.3
    command:
      - '-c'
      - 'fsync=off'
      - '-c'
      - 'full_page_writes=off'
      - '-c'
      - 'synchronous_commit=off'
      - '-c'
      - 'checkpoint_timeout=3600'
      - '-c'
      - 'max_wal_size=16000'
      - '-c'
      - 'listen_addresses=*'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=e-commerce
      - POSTGRES_USER=development
  migrations:
    image: node:14-alpine3.14
    volumes:
      - '.:/app'
      - /node_modules
      - /packages/frontend/node_modules
      - /packages/backend/node_modules
    working_dir: '/app'
    entrypoint: >
      sh -c "
        yarn && 
        yarn backend run migration:up
      "
    environment:
      - DATABASE_ADDRESS=postgres
  backend:
    image: node:14-alpine3.14
    volumes:
      - '.:/app'
      - /node_modules
      - /packages/frontend/node_modules
      - /packages/backend/node_modules
    working_dir: '/app'
    entrypoint: >
      sh -c "
        yarn && 
        yarn backend run develop
      "
    ports:
      - '5050:5050'
    environment:
      - DATABASE_ADDRESS=postgres
      - APP_HOST=0.0.0.0
