export enum ErrorCode {
  ERROR_VALIDATION = 'ERROR_VALIDATION',
  ERROR_UNAUTHORIZED = 'ERROR_UNAUTHORIZED',
  ERROR_MALFORMED_REQUEST = 'ERROR_MALFORMED_REQUEST',
  ERROR_NOT_FOUND = 'ERROR_NOT_FOUND',
  ERROR_INTERNAL = 'ERROR_INTERNAL',
  ERROR_UNKNOWN = 'ERROR_UNKNOWN',
  ERROR_FORBIDDEN = 'ERROR_FORBIDDEN',
}
