name: CI/CD

on: push

env:
  PNPM_VERSION: '6.10.2'

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - uses: AutoModality/action-clean@v1
      - name: Setup Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Setup pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Fetch HEAD + master
        run: git fetch origin master && git fetch origin $(git branch --show-current)


      - name: Run immutable install
        run: pnpm --frozen-lockfile install

      - name: Lint changed workspaces
        run: pnpm lint -- --format ./node_modules/eslint-junit

      - name: Publish Lint Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ github.token }}
          report_paths: '**/lint.xml'
          check_name: 'Lint Report'
          fail_if_no_tests: false

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ github.token }}
          report_paths: '**/junit.xml'
          check_name: 'Test Report'
          fail_if_no_tests: false
