name: CI/CD

on: push

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - name: Clean
        uses: AutoModality/action-clean@v1

      - name: Setup Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get Yarn Cache Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Immutable Install
        run: yarn install --frozen-lockfile

      - name: Lint All Packages
        run: yarn lint --format ./node_modules/eslint-junit

      - name: Test
        run: docker-compose up -d postgres migrations && yarn test
